version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: mouadh
      POSTGRES_PASSWORD: mouadh
      POSTGRES_DB: transformation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins
    container_name: jenkins_container
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
    postgres_data:
    pgadmin_data:
    jenkins_data:
