version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: mouadh
      POSTGRES_PASSWORD: mouadh
      POSTGRES_DB: transformation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: mouadh@mouadh.com
        PGADMIN_DEFAULT_PASSWORD: mouadh
    ports:
        - "5050:80"
    depends_on:
        - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
    postgres_data:
    pgadmin_data:

