# Generated by Django 5.1.7 on 2025-03-27 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfiguration',
            fields=[
                ('database_id', models.AutoField(primary_key=True, serialize=False)),
                ('database_type', models.CharField(max_length=50, unique=True)),
                ('config_parameters', models.JSONField()),
            ],
            options={
                'verbose_name': 'Database Configuration',
                'verbose_name_plural': 'Database Configurations',
                'db_table': 'database_configurations',
            },
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('database_metadata', models.JSONField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('github_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tool', models.CharField(choices=[('dbt', 'DBT'), ('sqlmesh', 'SQLMesh')], max_length=10)),
                ('user_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_type', models.ForeignKey(db_column='database_type', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='project_management.databaseconfiguration', to_field='database_type')),
            ],
            options={
                'verbose_name': 'Project Metadata',
                'verbose_name_plural': 'Projects Metadata',
                'db_table': 'project_metadata',
                'indexes': [models.Index(fields=['project_name'], name='project_met_project_a94985_idx'), models.Index(fields=['user_id'], name='project_met_user_id_cb8ba1_idx'), models.Index(fields=['is_active'], name='project_met_is_acti_5e49ae_idx')],
            },
        ),
    ]
