# Generated by Django 5.1.7 on 2025-03-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetadata',
            name='database_type',
            field=models.ForeignKey(db_column='database_type', on_delete=django.db.models.deletion.PROTECT, to='project_management.databaseconfiguration', to_field='database_type'),
        ),
    ]
