# Generated by Django 5.1.7 on 2025-04-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0003_alter_projectmetadata_database_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryIntegration',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_query', models.TextField()),
                ('adapted_query', models.JSONField()),
                ('target_tool', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.projectmetadata')),
            ],
            options={
                'db_table': 'query_integration',
            },
        ),
    ]
